root = "testdata"
# certfile ="./localhost.pem"
# keyfile ="./localhost-key.pem"
# reverse_proxy = "http://localhost:3000"

request_body_max_size = "100"

[[rules]]
from = "/public/from.html"
to = "/public/to.html"

[[headers]]
key = "X-Frame-Options"
value = "DENY"

[[headers]]
key = "X-Content-Type-Options"
value = "nosniff"

[log]
output = "stdout"
# file.path ="./niwa.log"
