name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.20]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download
      env:
        GO111MODULE: on

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Gosec
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Run test
      run: |
        go test -v ./...
      env:
        GO111MODULE: on

    - name: Build binary
      run: |
        go build

    - name: Run integration test
      run: |
        go run test/integration/main.go ./niwa -c test/integration/niw.toml
